# Generated by Django 2.0.3 on 2018-03-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_id', models.TextField(blank=True, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle', models.TextField(blank=True, null=True)),
                ('pickup', models.TextField(blank=True, null=True)),
                ('delivery', models.TextField(blank=True, null=True)),
                ('mileage', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('company', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('hour', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('posted', models.TextField(blank=True, null=True)),
                ('ship', models.TextField(blank=True, null=True)),
                ('scraped_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vehicles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailer', models.TextField()),
                ('number_of_cars', models.TextField()),
                ('miles_per_gallon', models.TextField()),
                ('cost_per_gallon', models.TextField()),
                ('pick_up_state', models.TextField()),
                ('pick_up_radius', models.TextField()),
                ('delivery', models.TextField()),
                ('delivery_radius', models.TextField()),
                ('minimum_cost_per_mile', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'trailer',
                'ordering': ('create_date',),
                'managed': True,
            },
        ),
    ]
