# Generated by Django 2.0.3 on 2018-03-22 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trailer', '0002_auto_20180321_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailer',
            name='highlighted',
        ),
        migrations.RemoveField(
            model_name='trailer',
            name='owner',
        ),
    ]
