# Generated by Django 2.0.3 on 2018-03-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailer', '0003_auto_20180322_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='create_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='update_date',
            field=models.DateTimeField(null=True),
        ),
    ]
