# Generated by Django 2.0.3 on 2018-03-23 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trailer', '0004_auto_20180322_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trailer',
            old_name='number_of_cars',
            new_name='capacity',
        ),
        migrations.AlterField(
            model_name='trailer',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
