# Generated by Django 2.0.3 on 2018-03-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailer', '0005_auto_20180323_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='pick_up_city',
            field=models.TextField(blank=True),
        ),
    ]
