# Generated by Django 2.0.3 on 2018-03-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailer', '0006_trailer_pick_up_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='capacity',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='cost_per_gallon',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='delivery',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='delivery_radius',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='miles_per_gallon',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='minimum_cost_per_mile',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='pick_up_radius',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='pick_up_state',
            field=models.TextField(blank=True),
        ),
    ]
