# Generated by Django 2.0.3 on 2018-03-23 20:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trailer', '0007_auto_20180323_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='capacity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='cost_per_gallon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='create_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='delivery',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='delivery_radius',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='miles_per_gallon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='minimum_cost_per_mile',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='pick_up_city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='pick_up_radius',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='pick_up_state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='trailer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='update_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
